
export function CarInforData() {
    var CarInfor= [
        {key: 'Acura'}, 
        {key: 'Audi'},      
        {key: 'BMW'},
        {key: 'Buick'},
        {key: 'Cadillac'}, 
        {key: 'Chevrolet'},
        {key: 'Citroen'},
        {key: 'Dodge'}, 
        {key: 'Fiat'},
        {key: 'Ford'},
        {key: 'GMC'},
        {key: 'Honda'},
        {key: 'Hummer'},
        {key: 'Huyndai'},
        {key: 'Infiniti'}, 
        {key: 'Isuzu'},
        {key: 'Jaguar'},
        {key: 'Jeep'},
        {key: 'Kia'},
        {key: 'Land Rover'},
        {key: 'Lexus'},
        {key: 'Lincoln'},
        {key: 'Mazda'},
        {key: 'Mercedes'},
        {key: 'Mercury'},
        {key: 'Mini'}, 
        {key: 'Mitsubishi'},
        {key: 'Nisan'},
        {key: 'Oldmobile'},
        {key: 'Pontiac'},
        {key: 'Saab'},
        {key: 'Saturn'},
        {key: 'Scion'},
        {key: 'Sabaru'},
        {key: 'Suzuki'},
        {key: 'Toyota'},
        {key: 'Volkswagen'}, 
        {key: 'Volvo'},
      ]
      return {CarInfor};
}

